Traceback (most recent call last):
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df_devices = ubi.get_available_devices_v2('bancolombia', 'group', page_size=100)
device_labels_with_data = list(set(df['device']))
has_data = df_devices['device_label'].isin(device_labels_with_data)
ids_with_data = list(df_devices.loc[has_data, 'device_id'])
df_map = ubi.get_gps_for_multiple_device_id(ids_with_data)

df_intensity = intensity.copy()
df_intensity = df_intensity.rename(columns={'yearly_kwh_per_m2':'value'})

df_map = pd.merge(
    df_map,
    # front_month[['device_name','value']],
    df_intensity,
    how='inner'
)

df_map = df_map.dropna(how='any')


fig = go.Figure()
fig.add_trace(go.Scattergeo(
    lon = df_map["longitude"],
    lat = df_map["latitude"],
    text = df_map["device_name"],
    marker = dict(
        size = df_map["value"],
        line_width=0.5,
        sizemode = 'area'
    )))


fig.update_layout(
    margin={"r":50,"t":50,"l":50,"b":50},
    geo = go.layout.Geo(
        resolution = 50,
        scope = 'south america',
        showframe = True,
        showcoastlines = True,
        landcolor = "rgb(229, 229, 229)",
        countrycolor = "white" ,
        coastlinecolor = "white",
        projection_type = 'mercator',
        lonaxis_range= [ -65.0, -85.0 ],
        lataxis_range= [ -5.0, 13.0 ],
        projection_scale=20))


fig.update_layout(title_text="Mapa de intensidad de consumo [kWh/m^2-aÃ±o]", font_size=12,width=750,height=500)
fig.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTimeoutError[0m                              Traceback (most recent call last)
File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\connectionpool.py:703[0m, in [0;36mHTTPConnectionPool.urlopen[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)[0m
[0;32m    702[0m [38;5;66;03m# Make the request on the httplib connection object.[39;00m
[1;32m--> 703[0m httplib_response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_make_request[49m[43m([49m
[0;32m    704[0m [43m    [49m[43mconn[49m[43m,[49m
[0;32m    705[0m [43m    [49m[43mmethod[49m[43m,[49m
[0;32m    706[0m [43m    [49m[43murl[49m[43m,[49m
[0;32m    707[0m [43m    [49m[43mtimeout[49m[38;5;241;43m=[39;49m[43mtimeout_obj[49m[43m,[49m
[0;32m    708[0m [43m    [49m[43mbody[49m[38;5;241;43m=[39;49m[43mbody[49m[43m,[49m
[0;32m    709[0m [43m    [49m[43mheaders[49m[38;5;241;43m=[39;49m[43mheaders[49m[43m,[49m
[0;32m    710[0m [43m    [49m[43mchunked[49m[38;5;241;43m=[39;49m[43mchunked[49m[43m,[49m
[0;32m    711[0m [43m[49m[43m)[49m
[0;32m    713[0m [38;5;66;03m# If we're going to release the connection in ``finally:``, then[39;00m
[0;32m    714[0m [38;5;66;03m# the response doesn't need to know about the connection. Otherwise[39;00m
[0;32m    715[0m [38;5;66;03m# it will also try to release it and we'll have a double-release[39;00m
[0;32m    716[0m [38;5;66;03m# mess.[39;00m

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\connectionpool.py:386[0m, in [0;36mHTTPConnectionPool._make_request[1;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)[0m
[0;32m    385[0m [38;5;28;01mtry[39;00m:
[1;32m--> 386[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_validate_conn[49m[43m([49m[43mconn[49m[43m)[49m
[0;32m    387[0m [38;5;28;01mexcept[39;00m (SocketTimeout, BaseSSLError) [38;5;28;01mas[39;00m e:
[0;32m    388[0m     [38;5;66;03m# Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.[39;00m

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\connectionpool.py:1042[0m, in [0;36mHTTPSConnectionPool._validate_conn[1;34m(self, conn)[0m
[0;32m   1041[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mgetattr[39m(conn, [38;5;124m"[39m[38;5;124msock[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m):  [38;5;66;03m# AppEngine might not have  `.sock`[39;00m
[1;32m-> 1042[0m     [43mconn[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m
[0;32m   1044[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m conn[38;5;241m.[39mis_verified:

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\connection.py:414[0m, in [0;36mHTTPSConnection.connect[1;34m(self)[0m
[0;32m    412[0m     context[38;5;241m.[39mload_default_certs()
[1;32m--> 414[0m [38;5;28mself[39m[38;5;241m.[39msock [38;5;241m=[39m [43mssl_wrap_socket[49m[43m([49m
[0;32m    415[0m [43m    [49m[43msock[49m[38;5;241;43m=[39;49m[43mconn[49m[43m,[49m
[0;32m    416[0m [43m    [49m[43mkeyfile[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mkey_file[49m[43m,[49m
[0;32m    417[0m [43m    [49m[43mcertfile[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcert_file[49m[43m,[49m
[0;32m    418[0m [43m    [49m[43mkey_password[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mkey_password[49m[43m,[49m
[0;32m    419[0m [43m    [49m[43mca_certs[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mca_certs[49m[43m,[49m
[0;32m    420[0m [43m    [49m[43mca_cert_dir[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mca_cert_dir[49m[43m,[49m
[0;32m    421[0m [43m    [49m[43mca_cert_data[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mca_cert_data[49m[43m,[49m
[0;32m    422[0m [43m    [49m[43mserver_hostname[49m[38;5;241;43m=[39;49m[43mserver_hostname[49m[43m,[49m
[0;32m    423[0m [43m    [49m[43mssl_context[49m[38;5;241;43m=[39;49m[43mcontext[49m[43m,[49m
[0;32m    424[0m [43m    [49m[43mtls_in_tls[49m[38;5;241;43m=[39;49m[43mtls_in_tls[49m[43m,[49m
[0;32m    425[0m [43m[49m[43m)[49m
[0;32m    427[0m [38;5;66;03m# If we're using all defaults and the connection[39;00m
[0;32m    428[0m [38;5;66;03m# is TLSv1 or TLSv1.1 we throw a DeprecationWarning[39;00m
[0;32m    429[0m [38;5;66;03m# for the host.[39;00m

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\util\ssl_.py:449[0m, in [0;36mssl_wrap_socket[1;34m(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)[0m
[0;32m    448[0m [38;5;28;01mif[39;00m send_sni:
[1;32m--> 449[0m     ssl_sock [38;5;241m=[39m [43m_ssl_wrap_socket_impl[49m[43m([49m
[0;32m    450[0m [43m        [49m[43msock[49m[43m,[49m[43m [49m[43mcontext[49m[43m,[49m[43m [49m[43mtls_in_tls[49m[43m,[49m[43m [49m[43mserver_hostname[49m[38;5;241;43m=[39;49m[43mserver_hostname[49m
[0;32m    451[0m [43m    [49m[43m)[49m
[0;32m    452[0m [38;5;28;01melse[39;00m:

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\util\ssl_.py:493[0m, in [0;36m_ssl_wrap_socket_impl[1;34m(sock, ssl_context, tls_in_tls, server_hostname)[0m
[0;32m    492[0m [38;5;28;01mif[39;00m server_hostname:
[1;32m--> 493[0m     [38;5;28;01mreturn[39;00m [43mssl_context[49m[38;5;241;43m.[39;49m[43mwrap_socket[49m[43m([49m[43msock[49m[43m,[49m[43m [49m[43mserver_hostname[49m[38;5;241;43m=[39;49m[43mserver_hostname[49m[43m)[49m
[0;32m    494[0m [38;5;28;01melse[39;00m:

File [1;32m~\.conda\envs\nuevo2-env\lib\ssl.py:501[0m, in [0;36mSSLContext.wrap_socket[1;34m(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)[0m
[0;32m    495[0m [38;5;28;01mdef[39;00m [38;5;21mwrap_socket[39m([38;5;28mself[39m, sock, server_side[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[0;32m    496[0m                 do_handshake_on_connect[38;5;241m=[39m[38;5;28;01mTrue[39;00m,
[0;32m    497[0m                 suppress_ragged_eofs[38;5;241m=[39m[38;5;28;01mTrue[39;00m,
[0;32m    498[0m                 server_hostname[38;5;241m=[39m[38;5;28;01mNone[39;00m, session[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[0;32m    499[0m     [38;5;66;03m# SSLSocket class handles server_hostname encoding before it calls[39;00m
[0;32m    500[0m     [38;5;66;03m# ctx._wrap_socket()[39;00m
[1;32m--> 501[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msslsocket_class[49m[38;5;241;43m.[39;49m[43m_create[49m[43m([49m
[0;32m    502[0m [43m        [49m[43msock[49m[38;5;241;43m=[39;49m[43msock[49m[43m,[49m
[0;32m    503[0m [43m        [49m[43mserver_side[49m[38;5;241;43m=[39;49m[43mserver_side[49m[43m,[49m
[0;32m    504[0m [43m        [49m[43mdo_handshake_on_connect[49m[38;5;241;43m=[39;49m[43mdo_handshake_on_connect[49m[43m,[49m
[0;32m    505[0m [43m        [49m[43msuppress_ragged_eofs[49m[38;5;241;43m=[39;49m[43msuppress_ragged_eofs[49m[43m,[49m
[0;32m    506[0m [43m        [49m[43mserver_hostname[49m[38;5;241;43m=[39;49m[43mserver_hostname[49m[43m,[49m
[0;32m    507[0m [43m        [49m[43mcontext[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[43m,[49m
[0;32m    508[0m [43m        [49m[43msession[49m[38;5;241;43m=[39;49m[43msession[49m
[0;32m    509[0m [43m    [49m[43m)[49m

File [1;32m~\.conda\envs\nuevo2-env\lib\ssl.py:1041[0m, in [0;36mSSLSocket._create[1;34m(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)[0m
[0;32m   1040[0m             [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mdo_handshake_on_connect should not be specified for non-blocking sockets[39m[38;5;124m"[39m)
[1;32m-> 1041[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdo_handshake[49m[43m([49m[43m)[49m
[0;32m   1042[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mOSError[39;00m, [38;5;167;01mValueError[39;00m):

File [1;32m~\.conda\envs\nuevo2-env\lib\ssl.py:1310[0m, in [0;36mSSLSocket.do_handshake[1;34m(self, block)[0m
[0;32m   1309[0m         [38;5;28mself[39m[38;5;241m.[39msettimeout([38;5;28;01mNone[39;00m)
[1;32m-> 1310[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_sslobj[49m[38;5;241;43m.[39;49m[43mdo_handshake[49m[43m([49m[43m)[49m
[0;32m   1311[0m [38;5;28;01mfinally[39;00m:

[1;31mTimeoutError[0m: [WinError 10060] Se produjo un error durante el intento de conexiÃ³n ya que la parte conectada no respondiÃ³ adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexiÃ³n establecida ya que el host conectado no ha podido responder

During handling of the above exception, another exception occurred:

[1;31mProtocolError[0m                             Traceback (most recent call last)
File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\requests\adapters.py:489[0m, in [0;36mHTTPAdapter.send[1;34m(self, request, stream, timeout, verify, cert, proxies)[0m
[0;32m    488[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m chunked:
[1;32m--> 489[0m     resp [38;5;241m=[39m [43mconn[49m[38;5;241;43m.[39;49m[43murlopen[49m[43m([49m
[0;32m    490[0m [43m        [49m[43mmethod[49m[38;5;241;43m=[39;49m[43mrequest[49m[38;5;241;43m.[39;49m[43mmethod[49m[43m,[49m
[0;32m    491[0m [43m        [49m[43murl[49m[38;5;241;43m=[39;49m[43murl[49m[43m,[49m
[0;32m    492[0m [43m        [49m[43mbody[49m[38;5;241;43m=[39;49m[43mrequest[49m[38;5;241;43m.[39;49m[43mbody[49m[43m,[49m
[0;32m    493[0m [43m        [49m[43mheaders[49m[38;5;241;43m=[39;49m[43mrequest[49m[38;5;241;43m.[39;49m[43mheaders[49m[43m,[49m
[0;32m    494[0m [43m        [49m[43mredirect[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m
[0;32m    495[0m [43m        [49m[43massert_same_host[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m
[0;32m    496[0m [43m        [49m[43mpreload_content[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m
[0;32m    497[0m [43m        [49m[43mdecode_content[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m
[0;32m    498[0m [43m        [49m[43mretries[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mmax_retries[49m[43m,[49m
[0;32m    499[0m [43m        [49m[43mtimeout[49m[38;5;241;43m=[39;49m[43mtimeout[49m[43m,[49m
[0;32m    500[0m [43m    [49m[43m)[49m
[0;32m    502[0m [38;5;66;03m# Send the request.[39;00m
[0;32m    503[0m [38;5;28;01melse[39;00m:

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\connectionpool.py:787[0m, in [0;36mHTTPConnectionPool.urlopen[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)[0m
[0;32m    785[0m     e [38;5;241m=[39m ProtocolError([38;5;124m"[39m[38;5;124mConnection aborted.[39m[38;5;124m"[39m, e)
[1;32m--> 787[0m retries [38;5;241m=[39m [43mretries[49m[38;5;241;43m.[39;49m[43mincrement[49m[43m([49m
[0;32m    788[0m [43m    [49m[43mmethod[49m[43m,[49m[43m [49m[43murl[49m[43m,[49m[43m [49m[43merror[49m[38;5;241;43m=[39;49m[43me[49m[43m,[49m[43m [49m[43m_pool[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43m_stacktrace[49m[38;5;241;43m=[39;49m[43msys[49m[38;5;241;43m.[39;49m[43mexc_info[49m[43m([49m[43m)[49m[43m[[49m[38;5;241;43m2[39;49m[43m][49m
[0;32m    789[0m [43m[49m[43m)[49m
[0;32m    790[0m retries[38;5;241m.[39msleep()

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\util\retry.py:550[0m, in [0;36mRetry.increment[1;34m(self, method, url, response, error, _pool, _stacktrace)[0m
[0;32m    549[0m [38;5;28;01mif[39;00m read [38;5;129;01mis[39;00m [38;5;28;01mFalse[39;00m [38;5;129;01mor[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_is_method_retryable(method):
[1;32m--> 550[0m     [38;5;28;01mraise[39;00m [43msix[49m[38;5;241;43m.[39;49m[43mreraise[49m[43m([49m[38;5;28;43mtype[39;49m[43m([49m[43merror[49m[43m)[49m[43m,[49m[43m [49m[43merror[49m[43m,[49m[43m [49m[43m_stacktrace[49m[43m)[49m
[0;32m    551[0m [38;5;28;01melif[39;00m read [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\packages\six.py:769[0m, in [0;36mreraise[1;34m(tp, value, tb)[0m
[0;32m    768[0m [38;5;28;01mif[39;00m value[38;5;241m.[39m__traceback__ [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m tb:
[1;32m--> 769[0m     [38;5;28;01mraise[39;00m value[38;5;241m.[39mwith_traceback(tb)
[0;32m    770[0m [38;5;28;01mraise[39;00m value

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\connectionpool.py:703[0m, in [0;36mHTTPConnectionPool.urlopen[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)[0m
[0;32m    702[0m [38;5;66;03m# Make the request on the httplib connection object.[39;00m
[1;32m--> 703[0m httplib_response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_make_request[49m[43m([49m
[0;32m    704[0m [43m    [49m[43mconn[49m[43m,[49m
[0;32m    705[0m [43m    [49m[43mmethod[49m[43m,[49m
[0;32m    706[0m [43m    [49m[43murl[49m[43m,[49m
[0;32m    707[0m [43m    [49m[43mtimeout[49m[38;5;241;43m=[39;49m[43mtimeout_obj[49m[43m,[49m
[0;32m    708[0m [43m    [49m[43mbody[49m[38;5;241;43m=[39;49m[43mbody[49m[43m,[49m
[0;32m    709[0m [43m    [49m[43mheaders[49m[38;5;241;43m=[39;49m[43mheaders[49m[43m,[49m
[0;32m    710[0m [43m    [49m[43mchunked[49m[38;5;241;43m=[39;49m[43mchunked[49m[43m,[49m
[0;32m    711[0m [43m[49m[43m)[49m
[0;32m    713[0m [38;5;66;03m# If we're going to release the connection in ``finally:``, then[39;00m
[0;32m    714[0m [38;5;66;03m# the response doesn't need to know about the connection. Otherwise[39;00m
[0;32m    715[0m [38;5;66;03m# it will also try to release it and we'll have a double-release[39;00m
[0;32m    716[0m [38;5;66;03m# mess.[39;00m

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\connectionpool.py:386[0m, in [0;36mHTTPConnectionPool._make_request[1;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)[0m
[0;32m    385[0m [38;5;28;01mtry[39;00m:
[1;32m--> 386[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_validate_conn[49m[43m([49m[43mconn[49m[43m)[49m
[0;32m    387[0m [38;5;28;01mexcept[39;00m (SocketTimeout, BaseSSLError) [38;5;28;01mas[39;00m e:
[0;32m    388[0m     [38;5;66;03m# Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.[39;00m

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\connectionpool.py:1042[0m, in [0;36mHTTPSConnectionPool._validate_conn[1;34m(self, conn)[0m
[0;32m   1041[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mgetattr[39m(conn, [38;5;124m"[39m[38;5;124msock[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m):  [38;5;66;03m# AppEngine might not have  `.sock`[39;00m
[1;32m-> 1042[0m     [43mconn[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m
[0;32m   1044[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m conn[38;5;241m.[39mis_verified:

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\connection.py:414[0m, in [0;36mHTTPSConnection.connect[1;34m(self)[0m
[0;32m    412[0m     context[38;5;241m.[39mload_default_certs()
[1;32m--> 414[0m [38;5;28mself[39m[38;5;241m.[39msock [38;5;241m=[39m [43mssl_wrap_socket[49m[43m([49m
[0;32m    415[0m [43m    [49m[43msock[49m[38;5;241;43m=[39;49m[43mconn[49m[43m,[49m
[0;32m    416[0m [43m    [49m[43mkeyfile[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mkey_file[49m[43m,[49m
[0;32m    417[0m [43m    [49m[43mcertfile[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcert_file[49m[43m,[49m
[0;32m    418[0m [43m    [49m[43mkey_password[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mkey_password[49m[43m,[49m
[0;32m    419[0m [43m    [49m[43mca_certs[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mca_certs[49m[43m,[49m
[0;32m    420[0m [43m    [49m[43mca_cert_dir[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mca_cert_dir[49m[43m,[49m
[0;32m    421[0m [43m    [49m[43mca_cert_data[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mca_cert_data[49m[43m,[49m
[0;32m    422[0m [43m    [49m[43mserver_hostname[49m[38;5;241;43m=[39;49m[43mserver_hostname[49m[43m,[49m
[0;32m    423[0m [43m    [49m[43mssl_context[49m[38;5;241;43m=[39;49m[43mcontext[49m[43m,[49m
[0;32m    424[0m [43m    [49m[43mtls_in_tls[49m[38;5;241;43m=[39;49m[43mtls_in_tls[49m[43m,[49m
[0;32m    425[0m [43m[49m[43m)[49m
[0;32m    427[0m [38;5;66;03m# If we're using all defaults and the connection[39;00m
[0;32m    428[0m [38;5;66;03m# is TLSv1 or TLSv1.1 we throw a DeprecationWarning[39;00m
[0;32m    429[0m [38;5;66;03m# for the host.[39;00m

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\util\ssl_.py:449[0m, in [0;36mssl_wrap_socket[1;34m(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)[0m
[0;32m    448[0m [38;5;28;01mif[39;00m send_sni:
[1;32m--> 449[0m     ssl_sock [38;5;241m=[39m [43m_ssl_wrap_socket_impl[49m[43m([49m
[0;32m    450[0m [43m        [49m[43msock[49m[43m,[49m[43m [49m[43mcontext[49m[43m,[49m[43m [49m[43mtls_in_tls[49m[43m,[49m[43m [49m[43mserver_hostname[49m[38;5;241;43m=[39;49m[43mserver_hostname[49m
[0;32m    451[0m [43m    [49m[43m)[49m
[0;32m    452[0m [38;5;28;01melse[39;00m:

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\urllib3\util\ssl_.py:493[0m, in [0;36m_ssl_wrap_socket_impl[1;34m(sock, ssl_context, tls_in_tls, server_hostname)[0m
[0;32m    492[0m [38;5;28;01mif[39;00m server_hostname:
[1;32m--> 493[0m     [38;5;28;01mreturn[39;00m [43mssl_context[49m[38;5;241;43m.[39;49m[43mwrap_socket[49m[43m([49m[43msock[49m[43m,[49m[43m [49m[43mserver_hostname[49m[38;5;241;43m=[39;49m[43mserver_hostname[49m[43m)[49m
[0;32m    494[0m [38;5;28;01melse[39;00m:

File [1;32m~\.conda\envs\nuevo2-env\lib\ssl.py:501[0m, in [0;36mSSLContext.wrap_socket[1;34m(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)[0m
[0;32m    495[0m [38;5;28;01mdef[39;00m [38;5;21mwrap_socket[39m([38;5;28mself[39m, sock, server_side[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[0;32m    496[0m                 do_handshake_on_connect[38;5;241m=[39m[38;5;28;01mTrue[39;00m,
[0;32m    497[0m                 suppress_ragged_eofs[38;5;241m=[39m[38;5;28;01mTrue[39;00m,
[0;32m    498[0m                 server_hostname[38;5;241m=[39m[38;5;28;01mNone[39;00m, session[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[0;32m    499[0m     [38;5;66;03m# SSLSocket class handles server_hostname encoding before it calls[39;00m
[0;32m    500[0m     [38;5;66;03m# ctx._wrap_socket()[39;00m
[1;32m--> 501[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msslsocket_class[49m[38;5;241;43m.[39;49m[43m_create[49m[43m([49m
[0;32m    502[0m [43m        [49m[43msock[49m[38;5;241;43m=[39;49m[43msock[49m[43m,[49m
[0;32m    503[0m [43m        [49m[43mserver_side[49m[38;5;241;43m=[39;49m[43mserver_side[49m[43m,[49m
[0;32m    504[0m [43m        [49m[43mdo_handshake_on_connect[49m[38;5;241;43m=[39;49m[43mdo_handshake_on_connect[49m[43m,[49m
[0;32m    505[0m [43m        [49m[43msuppress_ragged_eofs[49m[38;5;241;43m=[39;49m[43msuppress_ragged_eofs[49m[43m,[49m
[0;32m    506[0m [43m        [49m[43mserver_hostname[49m[38;5;241;43m=[39;49m[43mserver_hostname[49m[43m,[49m
[0;32m    507[0m [43m        [49m[43mcontext[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[43m,[49m
[0;32m    508[0m [43m        [49m[43msession[49m[38;5;241;43m=[39;49m[43msession[49m
[0;32m    509[0m [43m    [49m[43m)[49m

File [1;32m~\.conda\envs\nuevo2-env\lib\ssl.py:1041[0m, in [0;36mSSLSocket._create[1;34m(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)[0m
[0;32m   1040[0m             [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mdo_handshake_on_connect should not be specified for non-blocking sockets[39m[38;5;124m"[39m)
[1;32m-> 1041[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdo_handshake[49m[43m([49m[43m)[49m
[0;32m   1042[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mOSError[39;00m, [38;5;167;01mValueError[39;00m):

File [1;32m~\.conda\envs\nuevo2-env\lib\ssl.py:1310[0m, in [0;36mSSLSocket.do_handshake[1;34m(self, block)[0m
[0;32m   1309[0m         [38;5;28mself[39m[38;5;241m.[39msettimeout([38;5;28;01mNone[39;00m)
[1;32m-> 1310[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_sslobj[49m[38;5;241;43m.[39;49m[43mdo_handshake[49m[43m([49m[43m)[49m
[0;32m   1311[0m [38;5;28;01mfinally[39;00m:

[1;31mProtocolError[0m: ('Connection aborted.', TimeoutError(10060, 'Se produjo un error durante el intento de conexiÃ³n ya que la parte conectada no respondiÃ³ adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexiÃ³n establecida ya que el host conectado no ha podido responder', None, 10060, None))

During handling of the above exception, another exception occurred:

[1;31mConnectionError[0m                           Traceback (most recent call last)
Cell [1;32mIn[10], line 5[0m
[0;32m      3[0m has_data [38;5;241m=[39m df_devices[[38;5;124m'[39m[38;5;124mdevice_label[39m[38;5;124m'[39m][38;5;241m.[39misin(device_labels_with_data)
[0;32m      4[0m ids_with_data [38;5;241m=[39m [38;5;28mlist[39m(df_devices[38;5;241m.[39mloc[has_data, [38;5;124m'[39m[38;5;124mdevice_id[39m[38;5;124m'[39m])
[1;32m----> 5[0m df_map [38;5;241m=[39m [43mubi[49m[38;5;241;43m.[39;49m[43mget_gps_for_multiple_device_id[49m[43m([49m[43mids_with_data[49m[43m)[49m
[0;32m      7[0m df_intensity [38;5;241m=[39m intensity[38;5;241m.[39mcopy()
[0;32m      8[0m df_intensity [38;5;241m=[39m df_intensity[38;5;241m.[39mrename(columns[38;5;241m=[39m{[38;5;124m'[39m[38;5;124myearly_kwh_per_m2[39m[38;5;124m'[39m:[38;5;124m'[39m[38;5;124mvalue[39m[38;5;124m'[39m})

File [1;32mC:\Proyectos DigitalizaciÃ³n\Bancolombia\CB_Informe_Mensual\library_ubidots_v2.py:192[0m, in [0;36mUbidots.get_gps_for_multiple_device_id[1;34m(lst_device_ids, token)[0m
[0;32m    190[0m [38;5;28;01mfor[39;00m device [38;5;129;01min[39;00m lst_device_ids:
[0;32m    191[0m     pload [38;5;241m=[39m {[38;5;124m'[39m[38;5;124mtoken[39m[38;5;124m'[39m: token}
[1;32m--> 192[0m     r [38;5;241m=[39m [43mrequests[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m
[0;32m    193[0m [43m        [49m[38;5;124;43m'[39;49m[38;5;124;43mhttps://industrial.api.ubidots.com/api/v2.0/devices/[39;49m[38;5;124;43m'[39;49m
[0;32m    194[0m [43m        [49m[38;5;241;43m+[39;49m[43m [49m[38;5;28;43mstr[39;49m[43m([49m[43mdevice[49m[43m)[49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43m/?token=[39;49m[38;5;124;43m'[39;49m[38;5;241;43m+[39;49m[43mtoken[49m[43m,[49m[43m [49m[43mparams[49m[38;5;241;43m=[39;49m[43mpload[49m
[0;32m    195[0m [43m    [49m[43m)[49m
[0;32m    197[0m     JSON [38;5;241m=[39m r[38;5;241m.[39mjson()
[0;32m    199[0m     coords [38;5;241m=[39m {[38;5;124m"[39m[38;5;124mlat[39m[38;5;124m"[39m: [38;5;28;01mNone[39;00m, [38;5;124m"[39m[38;5;124mlng[39m[38;5;124m"[39m: [38;5;28;01mNone[39;00m}

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\requests\api.py:73[0m, in [0;36mget[1;34m(url, params, **kwargs)[0m
[0;32m     62[0m [38;5;28;01mdef[39;00m [38;5;21mget[39m(url, params[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m     63[0m [38;5;250m    [39m[38;5;124mr[39m[38;5;124;03m"""Sends a GET request.[39;00m
[0;32m     64[0m 
[0;32m     65[0m [38;5;124;03m    :param url: URL for the new :class:`Request` object.[39;00m
[1;32m   (...)[0m
[0;32m     70[0m [38;5;124;03m    :rtype: requests.Response[39;00m
[0;32m     71[0m [38;5;124;03m    """[39;00m
[1;32m---> 73[0m     [38;5;28;01mreturn[39;00m request([38;5;124m"[39m[38;5;124mget[39m[38;5;124m"[39m, url, params[38;5;241m=[39mparams, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\requests\api.py:59[0m, in [0;36mrequest[1;34m(method, url, **kwargs)[0m
[0;32m     55[0m [38;5;66;03m# By using the 'with' statement we are sure the session is closed, thus we[39;00m
[0;32m     56[0m [38;5;66;03m# avoid leaving sockets open which can trigger a ResourceWarning in some[39;00m
[0;32m     57[0m [38;5;66;03m# cases, and look like a memory leak in others.[39;00m
[0;32m     58[0m [38;5;28;01mwith[39;00m sessions[38;5;241m.[39mSession() [38;5;28;01mas[39;00m session:
[1;32m---> 59[0m     [38;5;28;01mreturn[39;00m session[38;5;241m.[39mrequest(method[38;5;241m=[39mmethod, url[38;5;241m=[39murl, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\requests\sessions.py:587[0m, in [0;36mSession.request[1;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)[0m
[0;32m    582[0m send_kwargs [38;5;241m=[39m {
[0;32m    583[0m     [38;5;124m"[39m[38;5;124mtimeout[39m[38;5;124m"[39m: timeout,
[0;32m    584[0m     [38;5;124m"[39m[38;5;124mallow_redirects[39m[38;5;124m"[39m: allow_redirects,
[0;32m    585[0m }
[0;32m    586[0m send_kwargs[38;5;241m.[39mupdate(settings)
[1;32m--> 587[0m resp [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39msend(prep, [38;5;241m*[39m[38;5;241m*[39msend_kwargs)
[0;32m    589[0m [38;5;28;01mreturn[39;00m resp

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\requests\sessions.py:701[0m, in [0;36mSession.send[1;34m(self, request, **kwargs)[0m
[0;32m    698[0m start [38;5;241m=[39m preferred_clock()
[0;32m    700[0m [38;5;66;03m# Send the request[39;00m
[1;32m--> 701[0m r [38;5;241m=[39m adapter[38;5;241m.[39msend(request, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m    703[0m [38;5;66;03m# Total elapsed time of the request (approximately)[39;00m
[0;32m    704[0m elapsed [38;5;241m=[39m preferred_clock() [38;5;241m-[39m start

File [1;32m~\.conda\envs\nuevo2-env\lib\site-packages\requests\adapters.py:547[0m, in [0;36mHTTPAdapter.send[1;34m(self, request, stream, timeout, verify, cert, proxies)[0m
[0;32m    544[0m             [38;5;28;01mraise[39;00m
[0;32m    546[0m [38;5;28;01mexcept[39;00m (ProtocolError, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m err:
[1;32m--> 547[0m     [38;5;28;01mraise[39;00m [38;5;167;01mConnectionError[39;00m(err, request[38;5;241m=[39mrequest)
[0;32m    549[0m [38;5;28;01mexcept[39;00m MaxRetryError [38;5;28;01mas[39;00m e:
[0;32m    550[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(e[38;5;241m.[39mreason, ConnectTimeoutError):
[0;32m    551[0m         [38;5;66;03m# TODO: Remove this in 3.0.0: see #2811[39;00m

[1;31mConnectionError[0m: ('Connection aborted.', TimeoutError(10060, 'Se produjo un error durante el intento de conexiÃ³n ya que la parte conectada no respondiÃ³ adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexiÃ³n establecida ya que el host conectado no ha podido responder', None, 10060, None))
ConnectionError: ('Connection aborted.', TimeoutError(10060, 'Se produjo un error durante el intento de conexiÃ³n ya que la parte conectada no respondiÃ³ adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexiÃ³n establecida ya que el host conectado no ha podido responder', None, 10060, None))

