Traceback (most recent call last):
  File "/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/anaconda3/envs/myenv/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cargas_hour = cargas.groupby(by=["variable"]).resample('1h').sum().round(2).reset_index().set_index('datetime')
cargas_hour = pro.datetime_attributes(cargas_hour)

cargas_day = cargas.groupby(by=["variable"]).resample('1D').sum().reset_index().set_index('datetime')
cargas_day = pro.datetime_attributes(cargas_day)

cargas_month = cargas.groupby(by=["variable"]).resample('1M').sum().reset_index().set_index('datetime')
cargas_month = pro.datetime_attributes(cargas_month)

front_hour = front.groupby(by=["variable"]).resample('1h').sum().round(2).reset_index().set_index('datetime')
front_hour = pro.datetime_attributes(front_hour)

front_day = front.groupby(by=["variable"]).resample('1D').sum().reset_index().set_index('datetime')
front_day = pro.datetime_attributes(front_day)

front_month = front.groupby(by=["variable"]).resample('1M').sum().reset_index().set_index('datetime')
front_month = pro.datetime_attributes(front_month)

#front_reactiva_hour = front_reactiva.groupby(by=["variable"]).resample('1h').sum().round(2).reset_index().set_index('datetime')
#front_reactiva_hour = pro.datetime_attributes(front_reactiva_hour)

front_pastmonth_month = front_pastmonth.groupby(by=["variable"]).resample('1M').sum().reset_index().set_index('datetime')
front_pastmonth_month = pro.datetime_attributes(front_pastmonth_month)

front_meses = front.groupby(by=["variable"]).resample('1M').sum().reset_index().set_index('datetime')
front_month = pro.datetime_attributes(front_month)

meses_agrupados = meses.groupby(['variable', pd.Grouper(freq='M')]).agg({'value': 'sum', 'hour': 'first', 'day': 'first', 'cont_dow': 'first', 'week': 'first', 'month': 'first', 'year': 'first', 'dow': 'first'}).reset_index()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/var/folders/_8/538vk3794fv7fbhk4ms0ks2r0000gp/T/ipykernel_7873/2013691524.py[0m in [0;36m?[0;34m()[0m
[1;32m      6[0m [0;34m[0m[0m
[1;32m      7[0m [0mcargas_month[0m [0;34m=[0m [0mcargas[0m[0;34m.[0m[0mgroupby[0m[0;34m([0m[0mby[0m[0;34m=[0m[0;34m[[0m[0;34m"variable"[0m[0;34m][0m[0;34m)[0m[0;34m.[0m[0mresample[0m[0;34m([0m[0;34m'1M'[0m[0;34m)[0m[0;34m.[0m[0msum[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mreset_index[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mset_index[0m[0;34m([0m[0;34m'datetime'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0mcargas_month[0m [0;34m=[0m [0mpro[0m[0;34m.[0m[0mdatetime_attributes[0m[0;34m([0m[0mcargas_month[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m [0;34m[0m[0m
[0;32m---> 10[0;31m [0mfront_hour[0m [0;34m=[0m [0mfront[0m[0;34m.[0m[0mgroupby[0m[0;34m([0m[0mby[0m[0;34m=[0m[0;34m[[0m[0;34m"variable"[0m[0;34m][0m[0;34m)[0m[0;34m.[0m[0mresample[0m[0;34m([0m[0;34m'1h'[0m[0;34m)[0m[0;34m.[0m[0msum[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mround[0m[0;34m([0m[0;36m2[0m[0;34m)[0m[0;34m.[0m[0mreset_index[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mset_index[0m[0;34m([0m[0;34m'datetime'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     11[0m [0mfront_hour[0m [0;34m=[0m [0mpro[0m[0;34m.[0m[0mdatetime_attributes[0m[0;34m([0m[0mfront_hour[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m [0;34m[0m[0m
[1;32m     13[0m [0mfront_day[0m [0;34m=[0m [0mfront[0m[0;34m.[0m[0mgroupby[0m[0;34m([0m[0mby[0m[0;34m=[0m[0;34m[[0m[0;34m"variable"[0m[0;34m][0m[0;34m)[0m[0;34m.[0m[0mresample[0m[0;34m([0m[0;34m'1D'[0m[0;34m)[0m[0;34m.[0m[0msum[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mreset_index[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mset_index[0m[0;34m([0m[0;34m'datetime'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/pandas/util/_decorators.py[0m in [0;36m?[0;34m(*args, **kwargs)[0m
[1;32m    327[0m                     [0mmsg[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0marguments[0m[0;34m=[0m[0m_format_argument_list[0m[0;34m([0m[0mallow_args[0m[0;34m)[0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    328[0m                     [0mFutureWarning[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    329[0m                     [0mstacklevel[0m[0;34m=[0m[0mfind_stack_level[0m[0;34m([0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    330[0m                 )
[0;32m--> 331[0;31m             [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/pandas/core/frame.py[0m in [0;36m?[0;34m(self, level, drop, inplace, col_level, col_fill, allow_duplicates, names)[0m
[1;32m   6357[0m                     level_values = algorithms.take(
[1;32m   6358[0m                         [0mlevel_values[0m[0;34m,[0m [0mlab[0m[0;34m,[0m [0mallow_fill[0m[0;34m=[0m[0;32mTrue[0m[0;34m,[0m [0mfill_value[0m[0;34m=[0m[0mlev[0m[0;34m.[0m[0m_na_value[0m[0;34m[0m[0;34m[0m[0m
[1;32m   6359[0m                     )
[1;32m   6360[0m [0;34m[0m[0m
[0;32m-> 6361[0;31m                 new_obj.insert(
[0m[1;32m   6362[0m                     [0;36m0[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   6363[0m                     [0mname[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   6364[0m                     [0mlevel_values[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/pandas/core/frame.py[0m in [0;36m?[0;34m(self, loc, column, value, allow_duplicates)[0m
[1;32m   4813[0m                 [0;34m"'self.flags.allows_duplicate_labels' is False."[0m[0;34m[0m[0;34m[0m[0m
[1;32m   4814[0m             )
[1;32m   4815[0m         [0;32mif[0m [0;32mnot[0m [0mallow_duplicates[0m [0;32mand[0m [0mcolumn[0m [0;32min[0m [0mself[0m[0;34m.[0m[0mcolumns[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   4816[0m             [0;31m# Should this be a different kind of error??[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 4817[0;31m             [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34mf"cannot insert {column}, already exists"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   4818[0m         [0;32mif[0m [0;32mnot[0m [0misinstance[0m[0;34m([0m[0mloc[0m[0;34m,[0m [0mint[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   4819[0m             [0;32mraise[0m [0mTypeError[0m[0;34m([0m[0;34m"loc must be int"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   4820[0m [0;34m[0m[0m

[0;31mValueError[0m: cannot insert variable, already exists

